### ISSUE TITLE
Stop file from being "hashed" when it is moved from the drop folder to the destination folder

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/ShokoServer#111]
When a file is hashed, and then moved from the drop folder to the destination folder, windows file move is used.

If that destination folder is also being watched, it triggers an event to hash that file again.
However this does actually hash the file again, but it does waste some time adding commands to the queues etc.

Make this smarter, so that if the file has just been hashed, do not add a command to the queue again.

**Comment by ElementalCrisis** [comment]
@da3dsoul was this something you fixed?

**Comment by da3dsoul** [comment]
Nope

**Comment by bigretromike** [comment]
This should be resolved now;

**Comment by da3dsoul** [comment]
This isn't fixed. It doesn't hash anymore, but it shouldn't need to import at all. I don't care enough to do it myself

**Comment by bigretromike** [comment]
it does not hash, and its just change path for file. whats wrong with it ?
